import type { PlaygroundConfig } from "./types";
import InputBox from "./showcases/InputBox";
import Button from "./showcases/Button";
import ToggleShowcase from "./showcases/Toggle";
import IconMorphShowcase from "./showcases/IconMorphShowcase";

export const playgroundRegistry: PlaygroundConfig[] = [
  {
    slug: "icon-morph",
    title: "Icon Morph",
    description:
      "The invisible bug in every copy button. Toggle between icons using opacity, scale, and blur the way state changes should feel.",
    Component: IconMorphShowcase,
    controls: [
      {
        key: "iconPair",
        label: "Icon pair",
        type: "select",
        default: "copy-check",
        group: "Display",
        options: [
          { value: "copy-check", label: "Copy → Check" },
          { value: "play-pause", label: "Play → Pause" },
          { value: "menu-x", label: "Menu → Close" },
          { value: "sun-moon", label: "Sun → Moon" },
        ],
      },
      {
        key: "autoToggle",
        label: "Auto-toggle demo",
        type: "toggle",
        default: false,
        group: "Display",
      },
      {
        key: "duration",
        label: "Duration",
        type: "slider",
        default: 300,
        min: 100,
        max: 800,
        step: 50,
        unit: "ms",
        group: "Timing",
      },
      {
        key: "enableOpacity",
        label: "Animate opacity",
        type: "toggle",
        default: true,
        group: "Opacity",
      },
      {
        key: "enableScale",
        label: "Animate scale",
        type: "toggle",
        default: true,
        group: "Scale",
      },
      {
        key: "scaleStart",
        label: "Scale from",
        type: "slider",
        default: 0.5,
        min: 0.2,
        max: 0.95,
        step: 0.05,
        group: "Scale",
      },
      {
        key: "enableBlur",
        label: "Animate blur",
        type: "toggle",
        default: true,
        group: "Blur",
      },
      {
        key: "blurAmount",
        label: "Blur amount",
        type: "slider",
        default: 4,
        min: 0,
        max: 12,
        step: 1,
        unit: "px",
        group: "Blur",
      },
    ],
  },
  {
    slug: "input-box",
    title: "Input Box",
    description:
      "A customizable text input. Play with size, radius, border, colors, and behavior in real time.",
    Component: InputBox,
    controls: [
      {
        key: "placeholder",
        label: "Placeholder",
        type: "text",
        default: "Type here...",
        group: "Content",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        default: "md",
        group: "Layout",
        options: [
          { value: "sm", label: "Small" },
          { value: "md", label: "Medium" },
          { value: "lg", label: "Large" },
        ],
      },
      {
        key: "radius",
        label: "Radius",
        type: "slider",
        default: 8,
        min: 0,
        max: 32,
        step: 1,
        unit: "px",
        group: "Layout",
      },
      {
        key: "borderWidth",
        label: "Border",
        type: "slider",
        default: 1,
        min: 0,
        max: 4,
        step: 1,
        unit: "px",
        group: "Layout",
      },
      {
        key: "borderColor",
        label: "Border color",
        type: "color",
        default: "#3f3f46",
        group: "Colors",
      },
      {
        key: "backgroundColor",
        label: "Background",
        type: "color",
        default: "#18181b",
        group: "Colors",
      },
      {
        key: "textColor",
        label: "Text color",
        type: "color",
        default: "#fafafa",
        group: "Colors",
      },
      {
        key: "showIcon",
        label: "Show icon",
        type: "toggle",
        default: true,
        group: "Behavior",
      },
      {
        key: "focusRing",
        label: "Focus ring",
        type: "toggle",
        default: true,
        group: "Behavior",
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "toggle",
        default: false,
        group: "Behavior",
      },
    ],
  },
  {
    slug: "button",
    title: "Button",
    description:
      "A fully customizable button. Change variants, size, icons, colors, and behavior.",
    Component: Button,
    controls: [
      {
        key: "label",
        label: "Label",
        type: "text",
        default: "Continue",
        group: "Content",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        default: "solid",
        group: "Style",
        options: [
          { value: "solid", label: "Solid" },
          { value: "outline", label: "Outline" },
          { value: "ghost", label: "Ghost" },
          { value: "soft", label: "Soft" },
        ],
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        default: "md",
        group: "Style",
        options: [
          { value: "sm", label: "Small" },
          { value: "md", label: "Medium" },
          { value: "lg", label: "Large" },
          { value: "xl", label: "Extra Large" },
        ],
      },
      {
        key: "radius",
        label: "Radius",
        type: "slider",
        default: 8,
        min: 0,
        max: 32,
        step: 1,
        unit: "px",
        group: "Style",
      },
      {
        key: "background",
        label: "Background",
        type: "color",
        default: "#3b82f6",
        group: "Colors",
      },
      {
        key: "foreground",
        label: "Text color",
        type: "color",
        default: "#ffffff",
        group: "Colors",
      },
      {
        key: "borderColor",
        label: "Border color",
        type: "color",
        default: "#3b82f6",
        group: "Colors",
      },
      {
        key: "borderWidth",
        label: "Border width",
        type: "slider",
        default: 1,
        min: 0,
        max: 4,
        step: 1,
        unit: "px",
        group: "Colors",
      },
      {
        key: "fontWeight",
        label: "Font weight",
        type: "slider",
        default: 500,
        min: 400,
        max: 700,
        step: 100,
        group: "Typography",
      },
      {
        key: "letterSpacing",
        label: "Letter spacing",
        type: "slider",
        default: 0,
        min: -1,
        max: 3,
        step: 0.1,
        unit: "px",
        group: "Typography",
      },
      {
        key: "uppercase",
        label: "Uppercase",
        type: "toggle",
        default: false,
        group: "Typography",
      },
      {
        key: "icon",
        label: "Icon",
        type: "select",
        default: "arrow",
        group: "Icon",
        options: [
          { value: "none", label: "None" },
          { value: "arrow", label: "Arrow" },
          { value: "check", label: "Check" },
          { value: "download", label: "Download" },
          { value: "github", label: "GitHub" },
          { value: "heart", label: "Heart" },
          { value: "plus", label: "Plus" },
          { value: "send", label: "Send" },
          { value: "sparkles", label: "Sparkles" },
          { value: "star", label: "Star" },
        ],
      },
      {
        key: "iconPosition",
        label: "Icon position",
        type: "select",
        default: "right",
        group: "Icon",
        options: [
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
        ],
      },
      {
        key: "fullWidth",
        label: "Full width",
        type: "toggle",
        default: false,
        group: "Behavior",
      },
      {
        key: "glow",
        label: "Glow",
        type: "toggle",
        default: false,
        group: "Behavior",
      },
      {
        key: "loading",
        label: "Loading",
        type: "toggle",
        default: false,
        group: "Behavior",
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "toggle",
        default: false,
        group: "Behavior",
      },
    ],
  },
  {
    slug: "toggle",
    title: "Toggle",
    description:
      "An animated switch. Tweak the size, shape, colors, icons, and label to fit your product.",
    Component: ToggleShowcase,
    controls: [
      {
        key: "size",
        label: "Size",
        type: "select",
        default: "md",
        group: "Layout",
        options: [
          { value: "sm", label: "Small" },
          { value: "md", label: "Medium" },
          { value: "lg", label: "Large" },
        ],
      },
      {
        key: "width",
        label: "Width",
        type: "slider",
        default: 44,
        min: 32,
        max: 80,
        step: 1,
        unit: "px",
        group: "Layout",
      },
      {
        key: "radius",
        label: "Radius",
        type: "slider",
        default: 999,
        min: 2,
        max: 999,
        step: 1,
        unit: "px",
        group: "Layout",
      },
      {
        key: "onColor",
        label: "On color",
        type: "color",
        default: "#3b82f6",
        group: "Colors",
      },
      {
        key: "offColor",
        label: "Off color",
        type: "color",
        default: "#3f3f46",
        group: "Colors",
      },
      {
        key: "thumbColor",
        label: "Thumb color",
        type: "color",
        default: "#ffffff",
        group: "Colors",
      },
      {
        key: "thumbShape",
        label: "Thumb shape",
        type: "select",
        default: "circle",
        group: "Thumb",
        options: [
          { value: "circle", label: "Circle" },
          { value: "pill", label: "Pill" },
          { value: "square", label: "Square" },
        ],
      },
      {
        key: "showIcons",
        label: "Show icons",
        type: "toggle",
        default: false,
        group: "Thumb",
      },
      {
        key: "iconStyle",
        label: "Icon style",
        type: "select",
        default: "check-x",
        group: "Thumb",
        options: [
          { value: "check-x", label: "Check / X" },
          { value: "sun-moon", label: "Sun / Moon" },
          { value: "none", label: "None" },
        ],
      },
      {
        key: "label",
        label: "Label",
        type: "text",
        default: "Enable notifications",
        group: "Label",
      },
      {
        key: "showLabel",
        label: "Show label",
        type: "toggle",
        default: true,
        group: "Label",
      },
      {
        key: "labelPosition",
        label: "Label position",
        type: "select",
        default: "left",
        group: "Label",
        options: [
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
        ],
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "toggle",
        default: false,
        group: "Behavior",
      },
      {
        key: "defaultOn",
        label: "Default on",
        type: "toggle",
        default: false,
        group: "Behavior",
      },
    ],
  },
];

export function getPlayground(slug: string): PlaygroundConfig | null {
  return playgroundRegistry.find((p) => p.slug === slug) ?? null;
}

export function getAllPlaygroundSlugs(): string[] {
  return playgroundRegistry.map((p) => p.slug);
}